include:
  - ../../constants.yml
targets:
  Albertos:
    type: application
    platform: iOS
    sources:
      - Albertos
      - ../../04-tdd-in-the-real-world/1-end/Albertos/AlbertosApp.swift
    scheme:
      testTargets: [AlbertosTests]
  AlbertosTests:
    target: Albertos
    type: bundle.unit-test
    platform: iOS
    sources:
      - AlbertosTests
      - ../../Packages/CollectionSafe/Sources/Collection+Safe.swift
    settings:
      # No need for code signing in this demo, plus, it's the test target
      CODE_SIGNING_ALLOWED: NO
    dependencies:
      - target: Albertos
