include:
  - ../../constants.yml
targets:
  Albertos:
    type: application
    platform: iOS
    sources: [Albertos]
    scheme:
      testTargets: [AlbertosTests]
    # settings:
    #   GENERATE_INFOPLIST_FILE: YES
    #   MARKETING_VERSION: 1.0
    #   CURRENT_PROJECT_VERSION: 0
  AlbertosTests:
    target: Albertos
    type: bundle.unit-test
    platform: iOS
    sources: [AlbertosTests]
    settings:
      # No need for code signing in this demo, plus, it's the test target
      CODE_SIGNING_ALLOWED: NO
    dependencies:
      - target: Albertos
