include:
  - ../../constants.yml
targets:
  Albertos:
    type: application
    platform: iOS
    sources:
      - ../../04-tdd-in-the-real-world/1-end/Albertos/MenuGrouping.swift
      - ../../06-testing-static-swiftui-views/1-end/Albertos/MenuRow.ViewModel.swift
      - ../../06-testing-static-swiftui-views/1-end/Albertos/MenuRow.swift
      - ../../06-testing-static-swiftui-views/1-end/Albertos/MenuSection.swift
      - ../../07-testing-dynamic-swiftui-views/1-end/Albertos/MenuFetching.swift
      - ../../08-stub/1-end/Albertos/MenuList.ViewModel.swift
      - ../../09-json-decoding/1-end/Albertos/MenuItem.swift
      - ../../10-networking/1-end/Albertos/MenuFetcher.swift
      - ../../10-networking/1-end/Albertos/NetworkFetching.swift
      - ../../10-networking/1-end/Albertos/URLSession+NetworkFetching.swift
      - ../0-start/Albertos/Color+Custom.swift
      - ../0-start/Albertos/Order.swift
      - ../0-start/Albertos/OrderButton.swift
      - ../0-start/Albertos/OrderButton.ViewModel.swift
      - ../0-start/Albertos/OrderController.swift
      - ../0-start/Albertos/OrderDetail.swift
      - ../0-start/Albertos/OrderDetail.ViewModel.swift
      - Albertos
    info:
      path: Albertos/Info.plist
      properties:
        UILaunchScreen:
          UIRequiredDeviceCapabilities: [armv7]
    scheme:
      testTargets: [AlbertosTests]
  AlbertosTests:
    target: Albertos
    type: bundle.unit-test
    platform: iOS
    sources:
      - ../../Packages/CollectionSafe/Sources/Collection+Safe.swift
      - ../../06-testing-static-swiftui-views/1-end/AlbertosTests/MenuGroupingTests.swift
      - ../../06-testing-static-swiftui-views/1-end/AlbertosTests/MenuItem+Fixture.swift
      - ../../06-testing-static-swiftui-views/1-end/AlbertosTests/MenuRow.ViewModelTests.swift
      - ../../06-testing-static-swiftui-views/1-end/AlbertosTests/MenuSection+Fixture.swift
      - ../../08-stub/1-end/AlbertosTests/MenuFetchingStub.swift
      - ../../08-stub/1-end/AlbertosTests/TestError.swift
      - ../../09-json-decoding/1-end/AlbertosTests/MenuItem+JSONFixture.swift
      - ../../09-json-decoding/1-end/AlbertosTests/MenuItemAlternateJSONTests.swift
      - ../../09-json-decoding/1-end/AlbertosTests/MenuItemTests.swift
      - ../../09-json-decoding/1-end/AlbertosTests/XCTestCase+JSON.swift
      - ../../09-json-decoding/1-end/AlbertosTests/menu_item.json
      - ../../10-networking/1-end/AlbertosTests/MenuFetcherTests.swift
      - ../../10-networking/1-end/AlbertosTests/MenuList.ViewModelTests.swift
      - ../../10-networking/1-end/AlbertosTests/NetworkFetchingStub.swift
      - ../0-start/AlbertosTests/OrderButtonViewModelTests.swift
      - ../0-start/AlbertosTests/OrderControllerTests.swift
      - ../0-start/AlbertosTests/OrderDetail.ViewModelTests.swift
      - ../0-start/AlbertosTests/OrderTests.swift
      - AlbertosTests
    settings:
      # No need for code signing in this demo, plus, it's the test target
      CODE_SIGNING_ALLOWED: NO
    dependencies:
      - target: Albertos
