include:
  - ../../constants.yml
targets:
  Albertos:
    type: application
    platform: iOS
    sources:
      - ../../04-tdd-in-the-real-world/1-end/Albertos/MenuGrouping.swift
      - ../../06-testing-static-swiftui-views/0-start/Albertos/Menu+Dummy.swift
      - ../../06-testing-static-swiftui-views/1-end/Albertos/MenuItem.swift
      - ../../06-testing-static-swiftui-views/1-end/Albertos/MenuList.swift
      - ../../06-testing-static-swiftui-views/1-end/Albertos/MenuRow.ViewModel.swift
      - ../../06-testing-static-swiftui-views/1-end/Albertos/MenuRow.swift
      - ../../06-testing-static-swiftui-views/1-end/Albertos/MenuSection.swift
      - Albertos
    scheme:
      testTargets: [AlbertosTests]
  AlbertosTests:
    target: Albertos
    type: bundle.unit-test
    platform: iOS
    sources:
      - ../../06-testing-static-swiftui-views/1-end/AlbertosTests/MenuGroupingTests.swift
      - ../../06-testing-static-swiftui-views/1-end/AlbertosTests/MenuItem+Fixture.swift
      - ../../06-testing-static-swiftui-views/1-end/AlbertosTests/MenuRow.ViewModelTests.swift
      - ../../06-testing-static-swiftui-views/1-end/AlbertosTests/MenuSection+Fixture.swift
      - AlbertosTests
      - ../../Packages/CollectionSafe/Sources/Collection+Safe.swift
    settings:
      # No need for code signing in this demo, plus, it's the test target
      CODE_SIGNING_ALLOWED: NO
    dependencies:
      - target: Albertos
